name: Build and Upload - Linux

on:
  push:
    branches:
      - nobridge

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [amd64, x86, arm64, armhf]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile main.py
        mv dist/main dist/umsktpy
        cp keys.json dist/keys.json

    - name: Run umsktpy
      run: |
        cd dist
        ./umsktpy

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: umsktpy-linux-${{ matrix.platform }}
        path: dist
